[global]
root-path-unix                              = '/tmp/iceoryx2/'
root-path-windows                           = 'c:\Temp\iceoryx2\'
prefix                                      = 'iox2_'

[global.node]
directory                                   = 'nodes'
monitor-suffix                              = '.node_monitor'
static-config-suffix                        = '.details'
service-tag-suffix                          = '.service_tag'
cleanup-dead-nodes-on-creation              = true
cleanup-dead-nodes-on-destruction           = true

[global.service]
directory                                   = 'services'
publisher-data-segment-suffix               = '.publisher_data'
static-config-storage-suffix                = '.service'
dynamic-config-storage-suffix               = '.dynamic'
event-connection-suffix                     = '.event'
connection-suffix                           = '.connection'
creation-timeout.secs                       = 0
creation-timeout.nanos                      = 500000000

[defaults.publish-subscribe]
max-subscribers                             = 8
max-publishers                              = 2
max-nodes                                   = 20
publisher-history-size                      = 1
subscriber-max-buffer-size                  = 2
subscriber-max-borrowed-samples             = 2
publisher-max-loaned-samples                = 2
enable-safe-overflow                        = true
unable-to-deliver-strategy                  = 'Block' # or 'DiscardSample'
subscriber-expired-connection-buffer        = 128

[defaults.event]
max-listeners                               = 2
max-notifiers                               = 16
max-nodes                                   = 36
event-id-max-value                          = 32
